#include<bits/stdc++.h>

using namespace std;

string MULTI_SPACE_0 =  "(\\s)*";
string MULTI_SPACE_1 =  "(\\s)+";
string REGISTER =  "[a-zA-z][0-9]";
string NUMBER = "[0-9]+";
string VARIABLE = "(("+NUMBER+")|("+REGISTER+"))";
string COMMA =  ",";
string SEPARATOR = "(("+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+")|("+MULTI_SPACE_1+"))";
string REGEX_ADD = MULTI_SPACE_0+"add"+MULTI_SPACE_1+REGISTER+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0+"(\\#)*"+".*";
string REGEX_ADDI = MULTI_SPACE_0+"addi"+MULTI_SPACE_1+REGISTER+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0;
string REGEX_SUB = MULTI_SPACE_0+"sub"+MULTI_SPACE_1+REGISTER+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0+"(\\#)*"+".*";
string REGEX_SUBI = MULTI_SPACE_0+"subi"+MULTI_SPACE_1+REGISTER+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0;
string REGEX_LA = MULTI_SPACE_0+"la"+MULTI_SPACE_1+REGISTER+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0;
string REGEX_LI = MULTI_SPACE_0+"li"+MULTI_SPACE_1+REGISTER+MULTI_SPACE_0+COMMA+MULTI_SPACE_0+VARIABLE+MULTI_SPACE_0;
string REGEX_ECALL = MULTI_SPACE_0+"ecall"+MULTI_SPACE_0;

map<string,int> opcount;

